version: '3.8'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  logstash:
    image: arm64v8/logstash:8.7.0
    container_name: logstash
    ports:
      - "5044:5044"
  elasticsearch:
    image: arm64v8/elasticsearch:8.7.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
  kibana:
    image: arm64v8/kibana:8.7.0
    container_name: kibana
    ports:
      - "5601:5601"